"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = PaymentPage;
var jsx_runtime_1 = require("react/jsx-runtime");
var react_router_dom_1 = require("react-router-dom");
var framer_motion_1 = require("framer-motion");
var lucide_react_1 = require("lucide-react");
var GlassNavbar_1 = require("../components/GlassNavbar");
var ScrollReveal_1 = require("../components/ScrollReveal");
var PaymentInfo_1 = require("../components/PaymentInfo");
function PaymentPage() {
    return ((0, jsx_runtime_1.jsxs)("div", { className: "min-h-screen bg-gradient-to-br from-indigo-50 via-purple-50 to-white font-sans", children: [(0, jsx_runtime_1.jsx)(GlassNavbar_1.default, {}), (0, jsx_runtime_1.jsxs)("div", { className: "max-w-2xl mx-auto px-4 py-10", children: [(0, jsx_runtime_1.jsx)(ScrollReveal_1.default, { children: (0, jsx_runtime_1.jsxs)(react_router_dom_1.Link, { to: "/", className: "inline-flex items-center gap-1.5 text-sm text-gray-500 hover:text-purple-700 mb-6 transition-colors", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.ArrowLeft, { size: 14 }), "Kembali ke Beranda"] }) }), (0, jsx_runtime_1.jsx)(ScrollReveal_1.default, { children: (0, jsx_runtime_1.jsxs)("div", { className: "text-center mb-8", children: [(0, jsx_runtime_1.jsx)(framer_motion_1.motion.div, { initial: { scale: 0 }, animate: { scale: 1 }, transition: { type: 'spring', stiffness: 200 }, className: "w-14 h-14 mx-auto mb-4 rounded-2xl bg-gradient-to-br from-purple-600 to-indigo-600 flex items-center justify-center shadow-lg shadow-purple-200", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Wallet, { size: 26, className: "text-white" }) }), (0, jsx_runtime_1.jsx)("h1", { className: "text-3xl font-extrabold text-gray-900 mb-2", children: "Pembayaran" }), (0, jsx_runtime_1.jsx)("p", { className: "text-gray-500 text-sm max-w-md mx-auto", children: "Pilih metode pembayaran yang paling mudah untuk Anda. Nomor bisa langsung disalin." })] }) }), (0, jsx_runtime_1.jsx)(ScrollReveal_1.default, { delay: 0.15, children: (0, jsx_runtime_1.jsx)(PaymentInfo_1.PaymentPageInline, {}) }), (0, jsx_runtime_1.jsx)(ScrollReveal_1.default, { delay: 0.3, children: (0, jsx_runtime_1.jsxs)("div", { className: "mt-8 grid grid-cols-1 sm:grid-cols-2 gap-4", children: [(0, jsx_runtime_1.jsx)(framer_motion_1.motion.div, { whileHover: { scale: 1.02 }, whileTap: { scale: 0.98 }, children: (0, jsx_runtime_1.jsxs)(react_router_dom_1.Link, { to: "/booking", className: "flex items-center justify-center gap-2 bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-700 hover:to-indigo-700 text-white font-bold py-3.5 rounded-2xl text-sm transition-all shadow-lg shadow-purple-200", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Zap, { size: 16 }), "Buat Booking Baru"] }) }), (0, jsx_runtime_1.jsxs)(framer_motion_1.motion.a, { whileHover: { scale: 1.02 }, whileTap: { scale: 0.98 }, href: "https://wa.me/6281295991378?text=Halo%2C%20saya%20sudah%20transfer%20dan%20mau%20kirim%20bukti%20pembayaran", target: "_blank", rel: "noopener noreferrer", className: "flex items-center justify-center gap-2 bg-green-500 hover:bg-green-400 text-white font-bold py-3.5 rounded-2xl text-sm transition-all shadow-lg shadow-green-200", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.MessageCircle, { size: 16 }), "Konfirmasi via WhatsApp"] })] }) })] })] }));
}
